apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-flask-app
  namespace: devops-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-flask-app
  template:
    metadata:
      labels:
        app: devops-flask-app
    spec:
      containers:
        - name: devops-flask-app
          image: kajal4321/devops-flask-app
          ports:
          - containerPort: 5000
      

