apiVersion: v1
kind: Service
metadata:
  name: service-flask-app
  namespace: devops-flask-app
spec:
  selector:
    app: devops-flask-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
